SET REFERENTIAL_INTEGRITY FALSE;
TRUNCATE TABLE companies RESTART IDENTITY;
TRUNCATE TABLE locations RESTART IDENTITY;
TRUNCATE TABLE meetings RESTART IDENTITY;
TRUNCATE TABLE users RESTART IDENTITY;
TRUNCATE TABLE users_meeting RESTART IDENTITY;